# Documentation / Swagger
springdoc:
    swagger-ui:
        disable-swagger-default-url: true
        path: /api

# Database / MongoDB
spring:
    data:
        mongodb:
            authentication-database: admin
            username: rootuser
            password: rootpass
            database: npamarkers
            port: 27017
            host: 172.19.100.10

# Security / JWT
jwt:
    access-token-expiration: 86400000
    refresh-token-expiration: 86400000