#file: noinspection SpringBootApplicationYaml
# Documentation / Swagger
springdoc:
    swagger-ui:
        disable-swagger-default-url: true
        path: /api

# Spring config
spring:
    data:
        mongodb:    # Database / MongoDB
            authentication-database: admin
            username: rootuser
            password: rootpass
            database: npamarkers
            port: 27017
            host: 172.19.100.10
    security:
        oauth2:     # Security / OAuth2.0
          client:
              registration:
                google:
                    client-id: ${CLIENT_ID}
                    client-secret: ${CLIENT_SECRET}
                    scope:
                      - email
                      - profile

# Security / JWT
jwt:
    access-token-expiration: 86400000
    refresh-token-expiration: 86400000